// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FontsController from "./fonts_controller"
application.register("fonts", FontsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import HarmonyController from "./harmony_controller"
application.register("harmony", HarmonyController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import CatalogueSidebarController from "./catalogue_sidebar_controller"
application.register("catalogue-sidebar", CatalogueSidebarController)
